.Dd $Mdocdate$
.Dt MTM 1
.Os
.Sh NAME
.Nm mtm
.Nd a micro-terminal multiplexer
.Sh SYNOPSIS
.Nm
.Op Fl m
.Op Fl u
.Op Fl c Ar CHARACTER
.Sh DESCRIPTION
.Nm
is a terminal multiplexer,
a program that allows multiple terminal sessions to run within a single
(physical or virtual)
terminal session.
.Nm
emulates a collection of
.Em mach
or
.Em mach-color
terminals.
.Pp
The options are
.Bl -tag -width Ds
.It Fl m
Run in monochrome mode;
do not use color of any sort.
By default,
.Nm
will run in color mode.
.It Fl u
Use Unicode box drawing characters;
this should be specified only if your system's wide-character type corresponds to Unicode.
.It Fl c Ar CHARACTER
Commands are prefixed using
.Ar CHARACTER
in combination with the
.Dq control
key.
By default this is
.Dq "g" "."
.El
.Pp
.Ss Usage
.Nm
divides the screen into multiple virtual terminals.
Each virtual terminal is updated and accessed independently.
At any given time,
exactly one virtual terminal is
.Dq focused ","
meaning that it receives any typed characters.
The currently-focused terminal is indicated by the location of the cursor.
.Pp
While running,
the following keys are recognized as commands to
.Nm
when prefixed with the command character:
.Bl -tag -width Ds
.It Em "Up/Down/Right/Left Arrow"
Select the terminal above/below/to the right of/to the left of the currently focused one.
.It Em "h" "or" "v"
Split the focused terminal in half horizontally
.Pq "for 'h'"
or vertically
.Pq "for 'v'" ";"
the newly-created terminal will be focused.
.It Em "w"
Delete the currently focused terminal.
.It Em "l"
.Pq "the letter ell"
Redraw the screen.
.El
.Pp
Note that these command keys,
and the default prefix,
can be changed at compile time and therefore may be different for this installation of
.Nm "."
.Pp
.Nm
will exit when its last virtual terminal is closed.
.Ss Colors
If the hosting terminal supports at least 80 color pairs
.Po
e.g.
.Em "xterm-256color"
but not plain
.Em xterm
.Pc ","
.Nm
will use the
.Pq natural
colors defined for the default virtual terminal forground and background colors.
.Pp
If the hosting terminal does not support at least 64 color pairs
.Pq "rare nowadays" ","
.Nm
will run in monochrome mode.
.Pp
Note that this does not affect the number of available color pairs within the virtual
terminals created by
.Nm ";"
this number remains fixed at either 64
.Pq "when run in color mode"
or 1
.Pq "when run in monochrome mode" "."
.Sh ENVIRONMENT
The following environment variables affect the operation of
.Nm mtm ":"
.Bl -tag -width Ds
.It Ev ESCDELAY
This variable specifies the number of milliseconds
.Nm
will wait after seeing an escape character for a special character sequence to complete.
By default this is 1000
.Pq "one second" "."
.It Ev LC_CTYPE Ev LC_ALL Ev LANG
These variables are consulted to determine the encoding used for textual data.
.It SHELL
If set,
.Nm
will launch the program named by this command in new virtual terminals.
If this is unset,
.Nm
will use the value of the
.Dq "command interpreter"
field of the password database
.Po
see
.Xr passwd 5
.Pc
if available,
and will finally use
.Pa "/bin/sh" "."
.Sh SEE ALSO
.Xr sh 1
.Sh BUGS
.Pp
Rendering of double-width characters will sometimes corrupt the display.
.Pp
.Nm
will attempt to fit all virtual terminals in the window at once.
If many terminals are created and the containing window is shrunk too small,
the display will be suboptimal.
.Pp
The only human language in which output is generated and in which documentation
is available is English,
regardless of the user's preferred language.
